"Resource/UI/HudItemEffectMeter_Demoman.res"
{
	HudItemEffectMeter
	{
		"fieldName"		"HudItemEffectMeter"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"-19"
		"ypos"			"r48"
		"wide"			"100"
		"tall"			"50"
		"MeterFG"		"White"
		"MeterBG"		"Gray"
	}
	"ItemEffectMeterLabel2"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ItemEffectMeterLabel2"
		"xpos"					"25"
		"ypos"					"27"
		"zpos"					"2"
		"wide"					"30"
		"tall"					"15"
		"autoResize"			"1"
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"Streak"
		"allcaps"               "0"
		"textAlignment"			"north"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"Game 10"
		"fgcolor"	     	      "gradientBUFF"		
		"bgcolor_override" "Gray30"
		"textinsetx" "2"
		"textinsety" "5"
	}
	"1gradient"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"1gradient"
		"xpos"	    		         				"0"
		"ypos"	    		         				"-1"
		"zpos"	    		         				"5"
		"wide"		    	         				"30"
		"tall"										"6"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"Streak"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 10"
		"fgcolor"	     	         				"gradientBUFF1"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"ItemEffectMeterLabel2"
	
		"alpha" "255"
	}
	"1gradient2"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"1gradient2"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"30"
		"tall"										"7"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"Streak"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 10"
		"fgcolor"	     	         				"gradientBUFF2"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"1gradient"

		"alpha" "255"
	}
	"1gradient3"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"1gradient3"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"30"
		"tall"										"8"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"Streak"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 10"
		"fgcolor"	     	         				"gradientBUFF3"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"1gradient2"

		"alpha" "255"
	}
	"1gradient4"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"1gradient4"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"30"
		"tall"										"9"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"Streak"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 10"
		"fgcolor"	     	         				"gradientBUFF4"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"1gradient3"

		"alpha" "255"
	}
	"1gradient5"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"1gradient5"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"30"
		"tall"										"10"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"Streak"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 10"
		"fgcolor"	     	         				"gradientBUFF5"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"1gradient4"

		"alpha" "255"
	}
	"1gradient6"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"1gradient6"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"30"
		"tall"										"11"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"Streak"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 10"
		"fgcolor"	     	         				"gradientBUFF6"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"1gradient5"

		"alpha" "255"
	}
	"1gradient7"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"1gradient7"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"30"
		"tall"										"12"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"Streak"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 10"
		"fgcolor"	     	         				"gradientBUFF7"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"1gradient6"

		"alpha" "255"
	}
	"1gradient8"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"1gradient8"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"30"
		"tall"										"13"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"Streak"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 10"
		"fgcolor"	     	         				"gradientBUFF8"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"1gradient7"

		"alpha" "255"
	}
	"1gradienshadow"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"1gradienshadow"
		"xpos"	    		         				"0"
		"ypos"	    		         				"-2"
		"zpos"	    		         				"5-1"
		"wide"		    	         				"30"
		"tall"		    	         				"13"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"Streak"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 10 Blur"
		"fgcolor"	     	         				"0 0 0 250"

		"pin_to_sibling" 							"1gradient8"
	}
	//Count
	"ItemEffectMeter"
	{	
		"ControlName"			"ContinuousProgressBar"
		"fieldName"				"ItemEffectMeter"
		"font"					"Default"
		"xpos"					"25"
		"ypos"					"23"
		"zpos"					"2"
		"wide"					"40"
		"tall"					"6"				
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"0"
		"textAlignment"			"Left"
		"dulltext"				"0"
		"brighttext"			"0"
	}					
	
	"ItemEffectMeterCount"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ItemEffectMeterCount"
		"xpos"					"-15"
		"ypos"					"27"
		"zpos"					"2"
		"wide"					"13"
		"tall"					"5"	
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"%progresscount%"
		"textAlignment"			"north"
		"dulltext"				"0"
		"brighttext"			"0"
		"fgcolor_override" "gradientBUFF"
		"font"					"Game 12"
		"textinsety" "3"
	}
	"gradient"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"gradient"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"13"
		"tall"										"6"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%progresscount%"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 12"
		"fgcolor"	     	         				"gradientBUFF1"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"ItemEffectMeterCount"
	
		"alpha" "255"
	}
	"gradient2"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"gradient2"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"										"7"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%progresscount%"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 12"
		"fgcolor"	     	         				"gradientBUFF2"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"gradient"

		"alpha" "255"
	}
	"gradient3"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"gradient3"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"										"8"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%progresscount%"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 12"
		"fgcolor"	     	         				"gradientBUFF3"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"gradient2"

		"alpha" "255"
	}
	"gradient4"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"gradient4"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"										"9"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%progresscount%"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 12"
		"fgcolor"	     	         				"gradientBUFF4"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"gradient3"

		"alpha" "255"
	}
	"gradient5"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"gradient5"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"										"10"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%progresscount%"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 12"
		"fgcolor"	     	         				"gradientBUFF5"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"gradient4"

		"alpha" "255"
	}
	"gradient6"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"gradient6"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"										"11"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%progresscount%"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 12"
		"fgcolor"	     	         				"gradientBUFF6"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"gradient5"

		"alpha" "255"
	}
	"gradient7"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"gradient7"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"										"12"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%progresscount%"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 12"
		"fgcolor"	     	         				"gradientBUFF7"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"gradient6"

		"alpha" "255"
	}
	"gradient8"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"gradient8"
		"xpos"	    		         				"0"
		"ypos"	    		         				"0"
		"zpos"	    		         				"5"
		"wide"		    	         				"150"
		"tall"										"13"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%progresscount%"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 12"
		"fgcolor"	     	         				"gradientBUFF8"
		"textinsety"							 "3"
		"dulltext"				"0"
		"brighttext"			"0"
		"tabPosition"			"0"

		"pin_to_sibling" 							"gradient7"

		"alpha" "255"
	}
	"gradienshadow"
	{
		"ControlName"	           				 	"CExLabel"
		"fieldName"	  	         				 	"gradienshadow"
		"xpos"	    		         				"0"
		"ypos"	    		         				"-2"
		"zpos"	    		         				"5-1"
		"wide"		    	         				"150"
		"tall"		    	         				"13"
		"visible"	    	         				"1"
		"enabled"	    	         				"1"
		"labelText"	  	         				 	"%progresscount%"
		"textAlignment"	         				 	"north"
		"font"                   				 	"Game 12 Blur"
		"fgcolor"	     	         				"0 0 0 250"

		"pin_to_sibling" 							"gradient8"
	}
	"ItemEffectMeterCountBG"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ItemEffectMeterCountBG"
		"xpos"					"55"
		"ypos"					"27"
		"zpos"					"2"
		"wide"					"11"
		"tall"					"15"	
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"textAlignment"			"north"
		"dulltext"				"0"
		"brighttext"			"0"
		"labelText" ""
		"textinsety" "3"
		"bgcolor_override" "Gray30"
	}
	// =======================================================================================================================
	"ItemEffectMeterBG"{"ControlName""CTFImagePanel""fieldName""ItemEffectMeterBG""xpos""9999""ypos""9999""wide""0""tall""0"	}
	"ItemEffectMeterLabel"{"ControlName""CExLabel""fieldName""ItemEffectMeterLabel""xpos""9999""ypos""9999""wide""0""tall""0""visible""0""enabled""0"}
}