"Resource/UI/HudItemEffectMeter.res"
{
	"HudItemEffectMeter"
	{
		"fieldName"									"HudItemEffectMeter"
		"xpos"										"cs-0.5"
		"ypos"										"c120"
		"zpos"										"0"
		"wide"										"100"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
	}
	"ItemEffectMeter"
	{
		"ControlName"								"ContinuousProgressBar"
		"fieldName"									"ItemEffectMeter"
		"xpos"										"cs-0.5"
		"ypos"										"cs-0.5"
		"zpos"										"0"
		"wide"										"f0"
		"tall"										"2"
		"visible"									"1"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"bgcolor_override" "Black"
	}
	"Mod"
	{
		"controlName"	"ImagePanel"	
		"fieldName"	"Mod"
		"xpos"	"0"	
		"ypos"	"0"	
		"zpos"	"3"	
		"wide"	"f0"	
		"tall"	"2"
		"visible"	"1"
		"enabled"	"1"	
		"image"	"replay/thumbnails/mod" 
		"scaleImage"	"1"
		
		"pin_to_sibling"	"ItemEffectMeter" 
	}
	"ItemEffectMeterLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"ItemEffectMeterLabel"
		"xpos"										"cs-0.5"
		"ypos"										"5"
		"zpos"										"2"
		"wide"										"f0"
		"tall"										"f0"
		"visible"									"1"
		"enabled"									"0"
		"proportionaltoparent"						"1"
		"labelText"									"#TF_Ball"
		"textAlignment"								"center"
		"font"										"Game 7"
		"disabledfgcolor2_override"					"White"
	}
}